# Generated by Django 4.0.2 on 2022-03-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('title2', models.CharField(max_length=100, verbose_name='Empresa que ofrecio el servicio')),
                ('Date', models.DateField(verbose_name='Fecha de termino del servicio')),
                ('description', models.TextField(verbose_name='Descripcion del servicio')),
                ('image', models.ImageField(upload_to='services', verbose_name='Imagen')),
                ('Number', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-Date'],
            },
        ),
    ]
