# Generated by Django 4.0.3 on 2022-04-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Number',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Costo del servicio'),
        ),
    ]
